package us.abstracta.jmeter.javadsl.core.listeners;

import java.time.Instant;
import java.util.HashMap;
import java.util.Map;
import org.apache.jmeter.config.Arguments;
import org.apache.jmeter.visualizers.backend.influxdb.InfluxdbBackendListenerClient;

/**
 * Test element which publishes all test run metrics to an InfluxDB instance.
 *
 * @since 0.4
 */
public class InfluxDbBackendListener extends DslBackendListener<InfluxDbBackendListener> {

  protected String title = "Test jmeter-java-dsl " + Instant.now().toString();
  protected String token;
  protected final Map<String, String> tags = new HashMap<>();
  protected String samplersRegex;
  protected String measurement;
  protected String applicationName;

  public InfluxDbBackendListener(String url) {
    super(InfluxdbBackendListenerClient.class, url);
  }

  /**
   * Allows setting a title for the test which will be included in started and ended annotations in
   * "events" measurement.
   * <p>
   * Consider setting this value to something that properly describes your application and the
   * particular test run (some timestamp, some CI/CD build ID, some commit ID, etc.).
   * <p>
   * When not specified, this will default to "jmeter-java-dsl" plus the current timestamp.
   *
   * @param title to be included in started and ended annotations.
   * @return the listener for further configuration or usage.
   */
  public InfluxDbBackendListener title(String title) {
    this.title = title;
    return this;
  }

  /**
   * Allows specifying a token for authentication with InfluxDB 2 instances.
   * <p>
   * Check <a href="https://docs.influxdata.com/influxdb/v2.0/security/">InfluxDB documentation</a>
   * for more details.
   *
   * @param token to use to authenticate to InfluxDB
   * @return the listener for further configuration or usage.
   */
  public InfluxDbBackendListener token(String token) {
    this.token = token;
    return this;
  }

  /**
   * Allows adding tags to be included with every measurement sent to InfluxDB.
   *
   * @param name  specifies the name of the tag. Take into consideration that, in contrast to JMeter
   *              GUI, no <pre>TAG_</pre> prefix should be included.
   * @param value specifies the value of the tag.
   * @return the listener for further configuration or usage.
   */
  public InfluxDbBackendListener tag(String name, String value) {
    tags.put(name, value);
    return this;
  }

  /**
   * Allows specifying the name of the measurement that contains collected metrics sent to
   * InfluxDB.
   *
   * @param measurement specifies the name of the measurement.
   * @return the listener for further configuration or usage.
   * @since 0.38
   */
  public InfluxDbBackendListener measurement(String measurement) {
    this.measurement = measurement;
    return this;
  }

  /**
   * Allows specifying an application name tag to be included with collected metrics.
   * <p>
   * This name can later be used to identify tests generated by this application on a given
   * measurement, from other applications.
   *
   * @param applicationName specifies the name of the application tag.
   * @return the listener for further configuration or usage.
   * @since 0.38
   */
  public InfluxDbBackendListener application(String applicationName) {
    this.applicationName = applicationName;
    return this;
  }

  /**
   * Allows specifying a regular expression used to filter collected metrics.
   * <p>
   * This regular expression is applied to sample labels, and when matched, collected sample metrics
   * will be sent to InfluxDB. Otherwise, they will be ignored.
   * <p>
   * For example ^[^_].*" - will exclude samplers which labels start with symbol "_".
   *
   * @param samplersRegex specifies the name of the samplersRegex.
   * @return the listener for further configuration or usage.
   * @since 0.38
   */
  public InfluxDbBackendListener samplersRegex(String samplersRegex) {
    this.samplersRegex = samplersRegex;
    return this;
  }

  @Override
  protected Arguments buildListenerArguments() {
    Arguments ret = new Arguments();
    ret.addArgument("influxdbUrl", url);
    ret.addArgument("summaryOnly", "false");
    ret.addArgument("testTitle", title);
    if (measurement != null) {
      ret.addArgument("measurement", measurement);
    }
    if (applicationName != null) {
      ret.addArgument("application", applicationName);
    }
    if (samplersRegex != null) {
      ret.addArgument("samplersRegex", samplersRegex);
    }
    if (token != null) {
      ret.addArgument("influxdbToken", token);
    }
    tags.forEach((name, value) -> ret.addArgument("TAG_" + name, value));
    return ret;
  }

}
