{
 "title": "JMeter Dashboard2",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "timeRange", "query": "10s" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "summarize(jmeter.all.a.count, '${timeRange}','sum',true)"
    }
   ]
  },
  {
   "title": "Failed Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "summarize(jmeter.all.ko.count,'${timeRange}','sum',true)"
    }
   ]
  },
  {
   "title": "Error Rate %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "divideSeries(summarize(jmeter.all.ko.count,'${timeRange}','sum',true),summarize(jmeter.all.a.count,'${timeRange}','sum',true))"
    }
   ]
  },
  {
   "title": "Total Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "target": "summarize(jmeter.all.a.count, '${__interval}', 'sum', true)"
    }
   ]
  },
  {
   "title": "Total Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "target": "summarize(jmeter.all.ko.count, '${__interval}','sum',true)"
    }
   ]
  },
  {
   "title": "Active Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 9 },
   "targets": [
    {
     "target": "summarize(jmeter.test.maxAT, '${__interval}', 'max', true)"
    }
   ]
  },
  {
   "title": "Transactions Response Times (95th pct)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "summarize(jmeter.all.ok.pct95, '${__interval}', 'average', true)"
    }
   ]
  }
 ]
}